import type { SceneDef } from './types'

export const SCENES: Record<SceneDef['id'], SceneDef> = {
  kitchen: {
    id: 'kitchen',
    title: '夜のキッチン',
    art: 'kitchen',
    hotspots: [
      {
        id: 'shion',
        label: 'しおん',
        x: 32,
        y: 54,
        w: 8,
        h: 18,
        actions: [
          {
            type: 'flag',
            flag: 'metShion',
            speaker: 'しおん',
            text: 'ようこそ、ほししおの島へ。今夜は月あかりポタージュをつくりたいの。ルナがメモを置いていったよ。',
          },
        ],
      },
      {
        id: 'luna',
        label: 'うさぎのルナ',
        x: 46,
        y: 52,
        w: 10,
        h: 18,
        hideWhen: ['lunaLeft'],
        actions: [
          {
            type: 'give',
            item: 'memo',
            speaker: 'ルナ',
            text: 'ぴょん。メモ、置いてく。月あかりポタージュ：星いも、月たまねぎ、月牛乳、星しお。窓から月のうら側へいけるよ。',
          },
          { type: 'flag', flag: 'gotMemo', speaker: 'ルナ', text: '足跡をたどってきて。先にいっちゃう。' },
          { type: 'flag', flag: 'lunaLeft', speaker: 'ルナ', text: '窓の向こうで待ってる。ぴょんっ。' },
        ],
      },
      {
        id: 'memoSpot',
        label: 'テーブルのメモ',
        x: 46,
        y: 56,
        w: 10,
        h: 16,
        showWhen: ['lunaLeft'],
        actions: [
          {
            type: 'say',
            speaker: 'メモ',
            text: '月あかりポタージュ：星いも、月たまねぎ、月牛乳、仕上げに星しお。',
          },
        ],
      },
      {
        id: 'window',
        label: '丸い窓',
        x: 52,
        y: 4,
        w: 28,
        h: 38,
        actions: [
          {
            type: 'flag',
            flag: 'windowOpen',
            speaker: 'しおん',
            text: '窓の向こうは星の道。月のうら側の畑につながっているよ。',
          },
          { type: 'go', scene: 'starRoad' },
        ],
      },
      {
        id: 'saltJar',
        label: '星しおの壺',
        x: 80,
        y: 32,
        w: 12,
        h: 20,
        hideWhen: ['saltTaken'],
        actions: [
          {
            type: 'give',
            item: 'starSalt',
            speaker: 'しおん',
            text: '島の特製、星しお。天の川の粒が少し混ざっているの。マヨネーズとはちがう、塩の魔法だよ。',
          },
          { type: 'flag', flag: 'saltTaken', speaker: 'しおん', text: 'ひとふりで星空の味。' },
        ],
      },
      {
        id: 'emptySalt',
        label: '空の壺',
        x: 80,
        y: 32,
        w: 12,
        h: 20,
        showWhen: ['saltTaken'],
        actions: [
          {
            type: 'say',
            speaker: 'しおん',
            text: '星しおはもうカバンのなか。大切にね。',
          },
        ],
      },
      {
        id: 'pot',
        label: 'お鍋',
        x: 18,
        y: 32,
        w: 16,
        h: 28,
        actions: [
          {
            type: 'say',
            speaker: 'しおん',
            text: 'まだ何も入っていない。材料がそろったら、ここで煮よう。',
          },
        ],
      },
      {
        id: 'clock',
        label: '星座時計',
        x: 18,
        y: 6,
        w: 16,
        h: 22,
        actions: [
          {
            type: 'say',
            speaker: '時計',
            text: '針はカシオペヤ座の形で止まっている。この島では夜が長く続く。',
          },
        ],
      },
      {
        id: 'lamp',
        label: '塩のランプ',
        x: 86,
        y: 8,
        w: 12,
        h: 24,
        actions: [
          {
            type: 'say',
            speaker: 'ランプ',
            text: '結晶がきらきらと、金の光をこぼしている。',
          },
        ],
      },
      {
        id: 'sink',
        label: '流し',
        x: 0,
        y: 40,
        w: 18,
        h: 32,
        actions: [
          {
            type: 'say',
            speaker: '流し',
            text: '水のかわりに、うすい星くずがさらさら流れている。つめたい。',
          },
        ],
      },
      {
        id: 'shelf',
        label: '調味料棚',
        x: 1,
        y: 8,
        w: 22,
        h: 22,
        actions: [
          {
            type: 'say',
            speaker: '棚',
            text: 'こしょうも砂糖もない。この島の味つけは、ほとんど星しおだけ。',
          },
        ],
      },
      {
        id: 'floorCrystal',
        label: '床の結晶',
        x: 82,
        y: 68,
        w: 14,
        h: 16,
        actions: [
          {
            type: 'say',
            speaker: '結晶',
            text: 'チリン。踏むたび、遠い星の音がする。',
          },
        ],
      },
      {
        id: 'cookStart',
        label: '料理をはじめる',
        x: 36,
        y: 68,
        w: 22,
        h: 12,
        requireItems: ['memo', 'potato', 'onion', 'moonMilk', 'starSalt'],
        missingText: 'まだ材料が足りないみたい。メモと、星いも、月たまねぎ、月牛乳、星しおがいるよ。',
        actions: [{ type: 'go', scene: 'cooking', speaker: 'しおん', text: 'そろったね。つくってみよう。' }],
      },
    ],
  },
  starRoad: {
    id: 'starRoad',
    title: '星の道',
    art: 'starRoad',
    hotspots: [
      {
        id: 'meteor',
        label: 'ながれ星',
        x: 4,
        y: 4,
        w: 28,
        h: 28,
        actions: [
          {
            type: 'say',
            speaker: 'ながれ星',
            text: 'きゅいん。願いごとは塩味だと叶いやすい、らしい。',
          },
        ],
      },
      {
        id: 'footprints',
        label: 'ルナの足跡',
        x: 28,
        y: 52,
        w: 28,
        h: 28,
        actions: [
          {
            type: 'say',
            speaker: '足跡',
            text: 'うさぎの足跡が、月のうら側へ続いている。',
          },
        ],
      },
      {
        id: 'toField',
        label: '月のうら側へ',
        x: 62,
        y: 8,
        w: 28,
        h: 48,
        actions: [{ type: 'go', scene: 'moonField', speaker: 'しおん', text: '空気が、塩っぽくなった。' }],
      },
      {
        id: 'backKitchen',
        label: 'キッチンへ戻る',
        x: 4,
        y: 78,
        w: 22,
        h: 14,
        actions: [{ type: 'go', scene: 'kitchen' }],
      },
    ],
  },
  moonField: {
    id: 'moonField',
    title: '月のうら側の畑',
    art: 'moonField',
    hotspots: [
      {
        id: 'potato',
        label: '星いも',
        x: 10,
        y: 42,
        w: 16,
        h: 22,
        actions: [
          {
            type: 'give',
            item: 'potato',
            speaker: '星いも',
            text: '土のなかで光っていたいも。ほくほくの星のかたち。',
          },
        ],
      },
      {
        id: 'onion',
        label: '月たまねぎ',
        x: 32,
        y: 40,
        w: 14,
        h: 20,
        actions: [
          {
            type: 'give',
            item: 'onion',
            speaker: '月たまねぎ',
            text: '層が三日月みたいに重なっている。切ると、塩の涙が出るらしい。',
          },
        ],
      },
      {
        id: 'earth',
        label: '遠くの青い星',
        x: 80,
        y: 4,
        w: 12,
        h: 14,
        actions: [
          {
            type: 'say',
            speaker: 'しおん',
            text: 'あれが地球。ここでは豆つぶみたい。',
          },
        ],
      },
      {
        id: 'crater',
        label: 'クレーター',
        x: 42,
        y: 52,
        w: 22,
        h: 24,
        actions: [
          {
            type: 'say',
            speaker: 'クレーター',
            text: 'なかはからっぽ。牛乳はもっと奥の洞窟だよ。',
          },
        ],
      },
      {
        id: 'toCave',
        label: '月の洞窟へ',
        x: 80,
        y: 26,
        w: 18,
        h: 26,
        actions: [{ type: 'go', scene: 'moonCave' }],
      },
      {
        id: 'backRoad',
        label: '星の道へ戻る',
        x: 4,
        y: 78,
        w: 22,
        h: 14,
        actions: [{ type: 'go', scene: 'starRoad' }],
      },
    ],
  },
  moonCave: {
    id: 'moonCave',
    title: '月の洞窟',
    art: 'moonCave',
    hotspots: [
      {
        id: 'well',
        label: '月の井戸',
        x: 36,
        y: 46,
        w: 26,
        h: 32,
        actions: [
          {
            type: 'give',
            item: 'moonMilk',
            speaker: '月の井戸',
            text: '静かな白い液体。飲むと、夢のなかで潮の音がする。',
          },
        ],
      },
      {
        id: 'stalactite',
        label: '塩の鍾乳石',
        x: 8,
        y: 0,
        w: 50,
        h: 22,
        actions: [
          {
            type: 'say',
            speaker: '鍾乳石',
            text: 'なめると、ほんの少しだけしょっぱい。',
          },
        ],
      },
      {
        id: 'echo',
        label: 'こだま',
        x: 78,
        y: 18,
        w: 18,
        h: 24,
        actions: [
          {
            type: 'say',
            speaker: 'こだま',
            text: '……しお。……しお。',
          },
        ],
      },
      {
        id: 'backField',
        label: '畑へ戻る',
        x: 4,
        y: 78,
        w: 22,
        h: 14,
        actions: [{ type: 'go', scene: 'moonField' }],
      },
    ],
  },
}
